<html>
  <head>
    <title>Silk API Documentation version $version$</title>
    <link rel="stylesheet" type="text/css" href="$static$/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="$static$/prettify.css">
    <link rel="stylesheet" type="text/css" href="$static$/docs.css">
    <script type="text/javascript" src="$static$/jquery-nightly.js"></script>
    <script type="text/javascript" src="$static$/bootstrap-modal.js"></script>
    <script type="text/javascript" src="$static$/prettify.js"></script>
    <script type="text/javascript" src="$static$/docs.js"></script>
  </head>
  <body>
    <div class="container-fluid">
      <div class="sidebar">
        <p>Silk API $version$</p>
        <div class="page-header">
          <h1>Resources</h1>
        </div>
        <ul>
          <li>
          $listing; separator="</li><li>"$
          </li>
        </ul>
      </div>
      <div class="content">
        
        <br/><br/>  
        $resources$
      </div>
    </div>
  </body>
</html>
